//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineDBEntities : DbContext
    {
        public CineDBEntities()
            : base("name=CineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiento> Asiento { get; set; }
        public virtual DbSet<Cine> Cine { get; set; }
        public virtual DbSet<CinePelicula> CinePelicula { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<Funcion> Funcion { get; set; }
        public virtual DbSet<Interprete> Interprete { get; set; }
        public virtual DbSet<Pelicula> Pelicula { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Protagonista> Protagonista { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
    }
}
