//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int CodTicket { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CodAsiento { get; set; }
        public Nullable<int> CodPersona { get; set; }
        public Nullable<int> CodFuncion { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
